#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := camera

EXTRA_COMPONENT_DIRS := $(CURDIR)/../components/pyxis
include $(IDF_PATH)/make/project.mk
